language: cpp
dist: bionic

os: 
  -linux
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y lcov libboost-all-dev python3-dev

install: true  

services: 
  - docker

jobs:
  include:
    - stage: building
      script:
        - mkdir -p build && cd build
        - cmake -DBUILD_TESTS=1 -DBUILD_ASAN=1 -DBUILD_PYTHON=1 -DPY_MODULE_WRAP_METHODS=1 -DCMAKE_BUILD_TYPE="Coverage" ../
        - make
        - env CTEST_OUTPUT_ON_FAILURE=1  make test
        - cd tests/performance
        - ./containers_performance
        - echo "Coverage"
        - cd ../
        - ./containers_tests
        - lcov --base-directory . --directory . -c -o coverage.info
        - lcov --remove coverage.info "/usr/*" "*submodules*" "*tests/tst_*" -o coverage.info 
        - lcov --summary coverage.info
    - stage: build-library-script
      script:
        - rm -rf build && mkdir build
        - ./build_library.sh build build -g++=/usr/bin/g++-7 
        - ls build/containers 
        - ls build/containers/queue 
        - ls build/containers/queue/queue.h 
        - ls build/containers/stack 
        - ls build/containers/stack/stack.h 
        - ls build/containers/bst 
        - ls build/containers/bst/bst.h 
        - ls build/containers/sorted_list 
        - ls build/containers/sorted_list/sorted_list.h 
        - ls build/containers/counter 
        - ls build/containers/counter/counter.h 
        - ls build/containers/staticarray 
        - ls build/containers/staticarray/staticarray.h 
        - for dir in build/containers/*; do ls $dir/extensions.h ; done
    - stage: run-docker-tests
      script:
        - ./run_docker_tests.sh

script:
  - echo ""
