language: cpp
dist: bionic

os: 
  -linux
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y lcov libboost-all-dev python3-dev

install: true  

services: 
  - docker

jobs:
  include:
    - stage: build-library
      script:
        - rm -rf build && mkdir build && cd build
        - cmake ../tests/
        - make
        - ./containers_tests
    - stage: build-coverage
      script:
        - rm -rf build && mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE="Coverage" ../tests/
        - make
        - ./containers_tests
        - lcov --base-directory . --directory . -c -o coverage.info
        - lcov --remove coverage.info "/usr/*" "*submodules*" "*tests/tst_*" -o coverage.info 
        - lcov --summary coverage.info
    - stage: build-performance
      script:
        - rm -rf build && mkdir build && cd build
        - cmake ../tests/performance
        - make
        - ./performance
    - stage: build-python-module
      script:
        - rm -rf build && mkdir build && cd build
        - cmake -DPY_MODULE_WRAP_METHODS=1 ../python/
        - make
        - cp ./containers.so ../python/tests/containers.so
        - cd ../python/tests/
        - python3 -m unittest discover -s ./ -p "tst_*.py"
    - stage: build-library-script
      script:
        - rm -rf build && mkdir build
        - ./build_library.sh build build -g++=/usr/bin/g++-7 
        - ls build/containers 
        - ls build/containers/queue 
        - ls build/containers/queue/queue.h 
        - ls build/containers/stack 
        - ls build/containers/stack/stack.h 
        - ls build/containers/bst 
        - ls build/containers/bst/bst.h 
        - ls build/containers/sorted_list 
        - ls build/containers/sorted_list/sorted_list.h 
        - ls build/containers/counter 
        - ls build/containers/counter/counter.h 
        - ls build/containers/staticarray 
        - ls build/containers/staticarray/staticarray.h 
        - for dir in build/containers/*; do ls $dir/extensions.h ; done
    - stage: run-docker-tests
      script:
        - ./run_docker_tests.sh

script:
  - echo ""
